<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-IT2FEOA" failures="0" tests="3" name="lumawebtesting.Place_order_while_checkout" time="10.144" errors="1" timestamp="2024-04-05T10:07:07 IST" skipped="0">
  <testcase classname="lumawebtesting.Place_order_while_checkout" name="HomePagetitleVerification" time="0.020"/>
  <system-out/>
  <testcase classname="lumawebtesting.Place_order_while_checkout" name="place_Order_checkout" time="9.320"/>
  <system-out/>
  <testcase classname="lumawebtesting.Place_order_while_checkout" name="data" time="0.804">
    <error message="
[public void lumawebtesting.Place_order_while_checkout.data(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.CharSequence[],java.lang.CharSequence[])] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: data([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=[Ljava.lang.CharSequence;, declaredAnnotations=[]}, Parameter{index=7, type=[Ljava.lang.CharSequence;, declaredAnnotations=[]}])
Arguments: [(java.lang.String) vaibhavbadgujar2314@gmail.com,(java.lang.String) Vaibhav,(java.lang.String) Badgujar,(java.lang.String) Abc,(java.lang.String) line no:99 pune maharashtra pune 99,(java.lang.String) Pune,(java.lang.String) 45632,(java.lang.String) 1234567890]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void lumawebtesting.Place_order_while_checkout.data(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.CharSequence[],java.lang.CharSequence[])] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: data([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=[Ljava.lang.CharSequence;, declaredAnnotations=[]}, Parameter{index=7, type=[Ljava.lang.CharSequence;, declaredAnnotations=[]}])
Arguments: [(java.lang.String) vaibhavbadgujar2314@gmail.com,(java.lang.String) Vaibhav,(java.lang.String) Badgujar,(java.lang.String) Abc,(java.lang.String) line no:99 pune maharashtra pune 99,(java.lang.String) Pune,(java.lang.String) 45632,(java.lang.String) 1234567890]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:914)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- data -->
  <system-out/>
</testsuite> <!-- lumawebtesting.Place_order_while_checkout -->
